; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:heltec_wifi_lora_32_V3]
platform = espressif32
board = heltec_wifi_lora_32_V3
framework = arduino
board_build.partitions = partitions_ota_ab.csv
build_flags =
  -Iinclude
  ; OTA profile selector: 0=dev, 1=production
  -DOTA_ACTIVE_PROFILE=OTA_PROFILE_PRODUCTION

lib_deps = 
  jgromes/RadioLib@^7.1.1
  https://github.com/ThingPulse/esp8266-oled-ssd1306.git
  adafruit/Adafruit SSD1306 @ ^2.5.7
  adafruit/Adafruit GFX Library @ ^1.11.5
  https://github.com/ropg/heltec_esp32_lora_v3.git
  https://github.com/ropg/LoRaWAN_ESP32.git
  h2zero/NimBLE-Arduino@^2.3.6
  h2zero/NimBLEOta@^0.2.0
  Heltec_ESP32_Display  ; OLED driver

monitor_speed = 115200